feat: Reuse census in different votings #24
egc-L5/decide-single-joaquin1 pull request #45
Opened 2023-11-28 17:39 UTC by Ignarrman

2023-11-29 09:50 UTC, barbaat commented
Buena nueva funcionalidad implementada, pero Codacy detecta algunos fallos. Revísalos y pide de nuevo la revisión.
¡Buen trabajo Nacho!

2023-11-29 09:51 UTC, barbaat requested changes
Revisa el Codacy

2023-11-30 00:42 UTC, Ignarrman commented
Me ha tomado varios commits arreglar los errores que me marcaba el Codacy pero ya deberían de pasar todos los tests

2023-11-30 07:30 UTC, barbaat approved these changes
Tienen muy buena pinta los cambios, Buena funcionalidad implementada

2023-11-30 07:30 UTC, merged